<a href="https://colab.research.google.com/github/kimalaacer/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/Tensors_Crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install torch


In [0]:
import torch
import numpy as np

In [0]:
v = torch.tensor([1,2,3, 4,5,6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [0]:
v.dtype

torch.int64

In [0]:
v[0]

tensor(1)

In [0]:
v[1:]

tensor([2, 3, 4, 5, 6])

In [0]:
f = torch.FloatTensor([1,2,3, 4,5,6])

In [0]:
f

tensor([1., 2., 3., 4., 5., 6.])

In [0]:
f.dtype

torch.float32

In [0]:
f.size()

torch.Size([6])

In [0]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [0]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [0]:
a = np.array([1,2,3,4,5])

In [0]:
a

array([1, 2, 3, 4, 5])

In [0]:
tensor_cnv = torch.from_numpy(a)

In [0]:
tensor_cnv

tensor([1, 2, 3, 4, 5])

In [0]:
tensor_cnv.dtype

torch.int64

In [0]:
tensor_cnv.type()

'torch.LongTensor'

In [0]:
print(a)

[1 2 3 4 5]


In [0]:
print(tensor_cnv)

tensor([1, 2, 3, 4, 5])


# New Section