<a href="https://colab.research.google.com/github/kimalaacer/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/Tutorial5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)

In [0]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)

In [0]:
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [0]:
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [0]:
torch.matmul(mat_a,mat_b)

tensor([[ 29, -16],
        [ 38,   6]])