<a href="https://colab.research.google.com/github/kimalaacer/PyTorch-for-Deep-Learning-and-Computer-Vision/blob/master/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch


In [0]:
one_d = torch.arange(0,9)

In [0]:
one_d


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
two_d = one_d.view(3,3)

In [0]:
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
two_d.dim()

2

In [0]:
two_d[2,2]

tensor(8)

In [0]:
x = torch.arange(0,18).view(2,3,3)

In [0]:
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [0]:
print(x)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


In [0]:
x3d = torch.arange(0,18).view(3,2,3)

In [0]:
x3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [0]:
x3d = torch.arange(0,18).view(3,3,2)

In [0]:
x3d

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])